from flask import Flask, render_template, request, jsonify
from unidecode import unidecode
import webbrowser
import threading

app = Flask(__name__)

# Dicionário com perguntas e respostas
faq = {
    "como vai": "Estou bem, obrigado! E você, como está?",
    "e ai": "E aí! O que posso fazer por você?",
    "saudacoes": "Saudações! Como posso ser útil hoje?",
    "bom dia pra você": "Bom dia! Espero que seu dia esteja indo bem!",
    "boa tarde pra você": "Boa tarde! Estou aqui para ajudar com o que precisar.",
    "boa noite pra você": "Boa noite! Como posso ajudar nesta noite?",
    "olá amigo": "Olá, amigo! O que posso fazer por você hoje?",
    "como você está": "Estou bem, obrigado! E você, como está se sentindo?",
    "oi pessoal": "Oi, pessoal! O que vocês gostariam de saber?",
    "como foi seu dia": "Meu dia está ótimo, obrigado! E o seu, como foi?",
    "olá a todos": "Olá a todos! Como posso ajudar vocês?",
    "e aí, beleza": "E aí, tudo certo? O que você precisa?",
    "que tal": "Que tal? Como posso ajudar você hoje?",
    "tudo tranquilo": "Tudo tranquilo! E você, como está?",
    "olá, como vai": "Olá! Como você está hoje?",
    "como anda": "Estou bem, e você? Como andam as coisas?",
    "como tem passado": "Estou passando bem, obrigado! E você, como tem passado?",
    "como está o clima": "Está ótimo! E por aí, como está o clima?",
    "olá, tudo certo": "Olá! Tudo certo por aqui. E você?",
    "bom dia, tudo bem": "Bom dia! Tudo bem por aqui, e com você?",
    "olá, feliz em te ver": "Olá! Fico feliz em te ver! Como posso ajudar?",
    "olá, como posso ajudar": "Olá! Estou aqui para ajudar. O que você precisa?",
    "oi, que bom te ver": "Oi! Que bom te ver! Como posso ajudar hoje?",
    "tudo em cima": "Tudo em cima! E com você, como está?",
    "só passando pra dizer oi": "Só passando para dizer oi! Como você está?",
    "prazer em conhecer": "Prazer em conhecer! Como posso ajudar?",
    "oi, tudo em ordem": "Oi! Tudo em ordem por aqui, e com você?",
    "olá, como vai você": "Olá! Como você está hoje?",
    "olá, tudo legal": "Olá! Tudo legal por aqui. E você?",
    "oi, boas vibrações": "Oi! Espero que esteja recebendo boas vibrações hoje!",
    "como vão as coisas": "As coisas vão bem, obrigado! E com você?",
    "bom dia, tudo certo por ai": "Bom dia! Tudo certo por aí?",
    "oi, espero que esteja bem": "Oi! Espero que você esteja bem hoje.",
    "olá, como foi seu dia": "Olá! Como foi seu dia até agora?",
    "como estão as coisas": "Estão indo bem! E com você, como estão as coisas?",
    "oi, estou aqui pra ajudar": "Oi! Estou aqui para ajudar com o que precisar.",
    "como tem sido seu dia": "Tem sido ótimo, obrigado! E o seu, como tem sido?",
    "bom dia, como está o seu dia": "Bom dia! Como está o seu dia até agora?",
    "oi, como está a vida": "Oi! Como está a vida tratando você?",
    "olá, tudo tranquilo por aqui": "Olá! Tudo tranquilo por aqui. E por aí?",
    "tudo na paz": "Tudo na paz! E você, tudo bem?",
    "como você tem se sentido": "Tenho me sentido bem, obrigado! E você, como tem se sentido?",
    "oi, que alegria te ver": "Oi! Que alegria te ver! Como posso ajudar?",
    "como vai sua semana": "Está indo bem, obrigado! E a sua, como vai?",
    "ola": "Olá! Como posso ajudar você hoje?",
    "tudo bem": "Tudo ótimo e com você?",
    "oi": "Oi! O que você precisa?",
    "bom dia": "Bom dia! Como posso ajudar você hoje?",
    "boa tarde": "Boa tarde! O que você gostaria de saber?",
    "boa noite": "Boa noite! Como posso assisti-lo?",
    "ate logo": "Até logo! Tenha um bom dia!",
    "sair": "Até logo! Se precisar, volte novamente.",
    # Tecnologia
    "o que e a nuvem": "A nuvem é um sistema que permite armazenar e acessar dados e programas pela internet ao invés de um disco rígido local.",
    "como funciona a criptomoeda": "As criptomoedas funcionam através de tecnologia de blockchain, que permite transações seguras e descentralizadas.",
    "o que e um aplicativo movel": "Um aplicativo móvel é um software projetado para rodar em dispositivos móveis, como smartphones e tablets.",
    "o que e um site": "Um site é um conjunto de páginas da web interconectadas que são acessadas via internet.",
    "o que e um virus de computador": "Um vírus de computador é um tipo de malware que se replica e se espalha de um computador para outro.",
    "como funciona o phishing": "Phishing é uma técnica de fraude onde um atacante tenta enganar as pessoas a fornecer informações confidenciais.",
    "o que e um sistema de gerenciamento de banco de dados": "Um SGBD é um software que permite criar, gerenciar e manipular bancos de dados.",
    "o que e a inteligencia artificial": "Inteligência artificial é a simulação de processos de inteligência humana por sistemas computacionais.",
    "como funciona a realidade aumentada": "A realidade aumentada combina elementos virtuais com o mundo real, geralmente usando a câmera de um dispositivo.",
    "o que e machine learning": "Machine learning é um ramo da inteligência artificial que permite que os computadores aprendam a partir de dados.",
    "o que e um algoritmo": "Um algoritmo é uma série de passos a serem seguidos para resolver um problema ou realizar uma tarefa.",
    "o que e o big data": "Big data refere-se a conjuntos de dados que são muito grandes ou complexos para serem processados por softwares convencionais.",
    "como funciona a tecnologia 5G": "A tecnologia 5G é a quinta geração de redes móveis, oferecendo velocidades de internet mais rápidas e conexões mais confiáveis.",
    "o que e um firewall": "Um firewall é uma barreira de segurança que controla o tráfego de rede, protegendo sistemas contra acessos não autorizados.",
    "o que e a computacao em nuvem": "Computação em nuvem é o fornecimento de serviços de computação (armazenamento, processamento, etc.) pela internet.",
    "como funciona a automacao industrial": "Automação industrial usa tecnologia para controlar processos e maquinários em indústrias, aumentando eficiência e segurança.",
    "o que e a internet das coisas": "A internet das coisas (IoT) refere-se a dispositivos conectados que podem coletar e compartilhar dados via internet.",
    "o que e um bot": "Um bot é um programa que automatiza tarefas, frequentemente usado para interagir com usuários em plataformas online.",
    "como funciona o reconhecimento facial": "Reconhecimento facial usa algoritmos para identificar ou verificar a identidade de uma pessoa a partir de uma imagem ou vídeo.",
    "o que e um sistema operacional": "Um sistema operacional é o software que gerencia o hardware e software de um computador ou dispositivo.",
    "o que e um servidor": "Um servidor é um computador ou sistema que fornece dados, recursos ou serviços para outros computadores na rede.",
    "como funciona a criptografia": "Criptografia é a prática de proteger informações convertendo-as em um formato codificado que só pode ser lido por quem possui a chave.",
    "o que e um site responsivo": "Um site responsivo é um site projetado para se adaptar a diferentes tamanhos de tela e dispositivos.",
    "o que e um CMS": "Um CMS (sistema de gerenciamento de conteúdo) é um software que permite criar e gerenciar conteúdo digital em um site.",
    "o que e um proxy": "Um proxy é um servidor que atua como intermediário entre um cliente e outro servidor, ajudando na privacidade e controle de acesso.",
    "o que e uma rede virtual privada (VPN)": "Uma VPN é uma tecnologia que cria uma conexão segura entre seu dispositivo e a internet, protegendo sua privacidade online.",
    "o que e a inteligencia de negocio": "Inteligência de negócio é um conjunto de estratégias e tecnologias usadas pelas empresas para analisar dados e tomar decisões informadas.",
    "como funciona o armazenamento em nuvem": "O armazenamento em nuvem permite que os usuários armazenem dados em servidores remotos acessíveis pela internet.",
    "o que e o machine vision": "Machine vision é a tecnologia que permite que máquinas e computadores 'vejam' e interpretem imagens, geralmente usando câmeras.",
    "o que e a blockchain": "Blockchain é uma tecnologia de registro distribuído que armazena dados em blocos interligados, garantindo segurança e transparência.",
    "como funciona a impressao 3D": "Impressão 3D é um processo que cria objetos físicos a partir de modelos digitais, utilizando camadas de material.",
    "o que e um hack": "Um hack é uma exploração de vulnerabilidades em sistemas para obter acesso não autorizado ou causar danos.",
    "como funciona o streaming": "Streaming é a transmissão de dados em tempo real pela internet, permitindo que os usuários assistam ou ouçam conteúdo sem precisar baixá-lo.",
    "o que e a ciberseguranca": "Cibersegurança é a prática de proteger sistemas, redes e programas de ataques digitais.",
    "o que e o desenvolvimento de software": "Desenvolvimento de software é o processo de criar, projetar, codificar e manter aplicações de software.",
    "como funciona a computacao quantica": "Computação quântica utiliza princípios da mecânica quântica para realizar cálculos mais rápidos que computadores clássicos.",
    "o que e um dispositivo wearable": "Um dispositivo wearable é um gadget que pode ser usado no corpo, como relógios inteligentes e rastreadores de fitness.",
    "o que e o design responsivo": "Design responsivo é uma abordagem que garante que as páginas da web sejam exibidas corretamente em diferentes dispositivos e tamanhos de tela.",
    "como funciona a autenticação de dois fatores": "A autenticação de dois fatores é um método de segurança que exige duas formas de verificação para acessar uma conta.",
    "o que e a realidade virtual": "Realidade virtual é uma simulação de um ambiente gerado por computador que pode ser explorado de forma interativa.",
    "como funciona a aprendizagem de maquina": "Aprendizagem de máquina é um ramo da inteligência artificial que utiliza algoritmos para analisar dados e aprender com eles.",
    "o que e um script": "Um script é um conjunto de instruções escritas em uma linguagem de programação que é executado por um interpretador.",
    "o que e um banco de dados relacional": "Um banco de dados relacional é um sistema de armazenamento de dados que organiza informações em tabelas inter-relacionadas.",
    "o que e a interface de programacao de aplicativos (API)": "Uma API é um conjunto de regras que permite que diferentes softwares se comuniquem entre si.",
    "como funciona a compressao de dados": "Compressão de dados é o processo de reduzir o tamanho de um arquivo para economizar espaço ou facilitar a transferência.",
    "o que e a virtualizacao": "Virtualização é a criação de uma versão virtual de um recurso, como servidores, armazenamento ou redes.",
    "o que e um sistema de controle de versao": "Um sistema de controle de versão é um software que registra alterações em arquivos ao longo do tempo, facilitando a colaboração.",
    "o que e o machine translation": "Machine translation é o uso de tecnologia para traduzir texto ou fala de uma língua para outra automaticamente.",
    "como funciona o processamento de linguagem natural": "Processamento de linguagem natural é uma área da inteligência artificial que permite que os computadores entendam e interpretem a linguagem humana.",
    # pitransportes
    
    "o que e a pitransportes": "pitransportes e um sistema de gerenciamento de transporte que otimiza a logistica de cargas.",
    "como a pitransportes melhora a eficiencia no transporte": "Através do planejamento inteligente de rotas e do monitoramento em tempo real das entregas.",
    "quais sao os principais beneficios da pitransportes": "Reducao de custos, aumento da produtividade e melhor rastreamento de cargas.",
    "a pitransportes pode ser integrada a outros sistemas": "Sim, ela pode ser integrada a sistemas de ERP e gerenciamento de armazem.",
    "como funciona o monitoramento em tempo real": "Utiliza GPS e sensores para acompanhar a localizacao e o status das cargas continuamente.",
    "quais tipos de transporte a pitransportes abrange": "Abrange transporte rodoviario, ferroviario, aereo e maritimo.",
    "a pitransportes e adequada para pequenas empresas": "Sim, o sistema e escalavel e pode ser utilizado por pequenas e grandes empresas.",
    "como a pitransportes ajuda na reducao de custos": "Ela otimiza rotas e melhora a utilizacao dos recursos, reduzindo gastos com combustivel e tempo.",
    "qual a importancia do rastreamento de cargas": "Permite que os clientes acompanhem suas entregas em tempo real, aumentando a confianca.",
    "como funciona a planificacao de rotas": "O sistema utiliza algoritmos para calcular as rotas mais eficientes com base em varios fatores.",
    "a pitransportes oferece suporte ao cliente": "Sim, ha uma equipe de suporte disponivel para ajudar os usuarios com qualquer duvida.",
    "quais sao os requisitos para usar a pitransportes": "Um computador ou dispositivo com acesso a internet e um navegador web.",
    "e possivel acessar a pitransportes de dispositivos moveis": "Sim, o sistema e responsivo e pode ser acessado por smartphones e tablets.",
    "quais funcionalidades a pitransportes oferece": "Inclui gerenciamento de frota, planejamento de rotas, rastreamento de cargas e relatorios.",
    "como a pitransportes melhora a comunicacao entre transportadoras": "Facilita o compartilhamento de informacoes e status em tempo real entre todos os envolvidos.",
    "a pitransportes permite agendar entregas": "Sim, e possivel agendar entregas conforme a disponibilidade do cliente.",
    "como a pitransportes garante a seguranca das cargas": "Implementa protocolos de rastreamento e monitoramento para prevenir roubos e perdas.",
    "quais industrias podem se beneficiar da pitransportes": "Industria alimenticia, farmacêutica, e-commerces e qualquer setor que depende de transporte de cargas.",
    "como a pitransportes auxilia na reducao de emissao de carbono": "Otimizando rotas e promovendo o uso de transportes mais sustentaveis.",
    "quais dados sao coletados pelo sistema": "Informacoes sobre rotas, status das entregas, e performance dos motoristas.",
    "e possivel personalizar o sistema pitransportes": "Sim, o sistema pode ser personalizado conforme as necessidades da empresa.",
    "a pitransportes oferece relatorios de desempenho": "Sim, fornece relatorios detalhados sobre a eficiencia e performance das operacoes.",
    "quais sao as ferramentas de analise disponiveis": "Ferramentas de analise de dados, dashboards e visualizacao de informacoes em tempo real.",
    "como a pitransportes facilita a gestao de frota": "Permite monitorar o desempenho dos veiculos e programar manutenções.",
    "a pitransportes possui suporte tecnico": "Sim, ha suporte tecnico para resolver problemas e duvidas dos usuarios.",
    "como a pitransportes lida com emergencias": "Possui planos de contingencia e comunicação para resolver problemas rapidamente.",
    "quais sao as opcoes de pagamento": "O sistema pode integrar diferentes opcoes de pagamento conforme a necessidade do cliente.",
    "como a pitransportes se destaca da concorrencia": "Oferece funcionalidades completas e suporte proativo aos usuarios.",
    "a pitransportes permite a gestao de varias filiais": "Sim, e possivel gerenciar varias filiais a partir de um unico sistema.",
    "como funciona o cadastro de usuarios": "Os administradores podem cadastrar e gerenciar usuarios diretamente no sistema.",
    "quais sao os protocolos de seguranca da pitransportes": "Implementa criptografia e acesso restrito para proteger as informacoes dos usuarios.",
    "como a pitransportes garante a conformidade regulatoria": "O sistema e atualizado regularmente para atender as normativas do setor.",
    "quais sao os custos de implementacao do sistema": "Os custos variam conforme as funcionalidades e personalizacoes desejadas.",
    "a pitransportes oferece treinamento para novos usuarios": "Sim, ha programas de treinamento para garantir que os usuarios saibam como utilizar o sistema.",
    "como a pitransportes facilita o relacionamento com clientes": "Permite um acompanhamento mais proximo das entregas e feedback em tempo real.",
    "a pitransportes pode ser utilizada em outros paises": "Sim, e possivel utilizar o sistema em diferentes localidades conforme a necessidade.",
    "como a pitransportes auxilia no planejamento de cargas": "Ajuda a planejar o carregamento de forma mais eficiente, considerando peso e dimensoes.",
    "a pitransportes pode ser acessada offline": "O acesso ao sistema requer conectividade com a internet.",
    "como a pitransportes facilita o controle de inventario": "Permite monitorar o estoque de cargas e otimizar a logistica de armazens.",
    "quais sao as opcoes de suporte ao cliente": "Suporte por telefone, e-mail e chat online.",
    "a pitransportes e adequada para grandes empresas": "Sim, o sistema foi projetado para atender tanto pequenas quanto grandes empresas.",
    "como a pitransportes auxilia na gestao de custos": "Oferece analises detalhadas que ajudam a identificar areas de economia.",
    "quais sao os feedbacks dos usuarios sobre a pitransportes": "Os usuarios geralmente destacam a facilidade de uso e a eficiencia do sistema.",
    "a pitransportes permite agendamento de coletas": "Sim, e possivel agendar coletas conforme a disponibilidade do cliente.",
    "como a pitransportes melhora a transparencia nas operacoes": "Oferece acesso a informacoes em tempo real sobre o status das entregas.",
    "quais sao as possibilidades de personalizacao do sistema": "Os usuarios podem personalizar relatorios, dashboards e notificacoes.",
    # logistica
    "como a tecnologia melhora a gestao da cadeia de suprimentos": "facilita a comunicacao e a colaboracao entre os parceiros.",
    "quais sao os principais desafios da logistica": "gerenciamento de custos, atrasos nas entregas e variabilidade na demanda.",
    "como o big data pode ser utilizado na logistica": "analisa grandes volumes de dados para identificar tendencias e otimizar processos.",
    "qual a importancia da logistica reversa": "permite a devolucao de produtos e reduz desperdicios.",
    "como a automacao de armazens aumenta a produtividade": "utiliza sistemas robotizados para agilizar o armazenamento e a separacao de pedidos.",
    "quais sao os beneficios do uso de drones na entrega": "reduz o tempo de entrega e acessa locais de dificil acesso.",
    "como a sustentabilidade impacta as operacoes logisticas": "promove a reducao de emissao de carbono e o uso de recursos renovaveis.",
    "quais sao as tendencias atuais na logistica": "logistica sob demanda, entrega no mesmo dia e uso de inteligencia artificial.",
    "como a tecnologia RFID auxilia no controle de inventario": "permite o rastreamento em tempo real de produtos no estoque.",
    "quais sao os principais indicadores de desempenho logístico": "tempo de entrega, custo por entrega e taxa de cumprimento de pedidos.",
    "como a logistica impacta a experiencia do cliente": "entregas pontuais e precisas aumentam a satisfacao do cliente.",
    "quais sao as vantagens do uso de softwares de gerenciamento logístico": "centralizam informacoes e melhoram a tomada de decisao.",
    "como a comunicacao eficaz melhora a logistica": "evita mal-entendidos e aumenta a eficiencia das operacoes.",
    "quais sao as funcoes do operador logístico": "gerenciar transporte, armazenagem e distribuicao de produtos.",
    "como a previsao de demanda influencia a logistica": "ajuda a planejar o estoque e a capacidade de transporte.",
    "quais sao os custos envolvidos na logistica": "transporte, armazenagem, manuseio e seguro.",
    "como a colaboracao entre empresas melhora a logistica": "permite compartilhar recursos e reduzir custos operacionais.",
    "quais sao os riscos na cadeia de suprimentos": "atrasos, interrupcoes e flutuacoes de preco.",
    "como a analise de dados pode reduzir custos logísticos": "identifica ineficiencias e oportunidades de melhoria.",
    "quais sao os beneficios do cross-docking na logistica": "reduz o tempo de armazenamento e acelera o fluxo de mercadorias.",
    "como o planejamento logístico pode melhorar a competitividade": "permite uma melhor alocacao de recursos e aumento da eficiencia.",
    "quais sao as melhores praticas de embalagem na logistica": "garantir a protecao dos produtos e otimizar o espaco no transporte.",
    "como as tecnologias de blockchain podem ser aplicadas na logistica": "aumentam a transparência e a seguranca nas transacoes.",
    "quais sao os impactos da globalizacao na logistica": "amplia as oportunidades de mercado e aumenta a complexidade das operacoes.",
    "como a logistica de ultima milha pode ser otimizada": "utilizando tecnologias para rastreamento e planejamento de rotas.",
    "quais sao as vantagens de um centro de distribuicao": "permite uma melhor geracao de valor e agilidade na entrega.",
    "como a gestao de riscos pode ser aplicada na logistica": "identificando e mitigando potenciais problemas nas operacoes.",
    "quais sao as tecnologias emergentes na logistica": "inteligencia artificial, automacao e IoT.",
    "como a cultura organizacional afeta a logistica": "impacta a eficiencia e a adaptabilidade das operacoes logísticas.",
    "quais sao os beneficios do transporte intermodal": "reduz custos e melhora a eficiencia na movimentacao de cargas.",
    "como o uso de aplicativos de transporte pode beneficiar a logistica": "aumenta a visibilidade e permite melhor gerenciamento de rotas.",
    "quais sao os requisitos legais para a operacao logistica": "licencas, regulacoes de transporte e normas de segurança.",
    "como a manutencao preventiva pode reduzir custos logísticos": "evita paradas inesperadas e prolonga a vida util dos equipamentos.",
    "quais sao os principais desafios do transporte internacional": "regulacoes aduaneiras, custos e variabilidade nas rotas.",
    "como a experiencia do consumidor influencia as operacoes logísticas": "os consumidores exigem maior rapidez e transparencia nas entregas.",
    "quais sao os principais tipos de transporte utilizados na logistica": "rodoviario, ferroviario, aquaviario e aereo.",
    "como o gerenciamento de estoque impacta a logistica": "afeta a disponibilidade de produtos e o tempo de atendimento.",
    "quais sao as vantagens do uso de sistemas de gerenciamento de armazens (WMS)": "melhora a eficiencia e a precisao no controle de inventario.",
    "como a automacao pode reduzir o erro humano na logistica": "utiliza sistemas para realizar tarefas repetitivas com maior precisao.",
    "quais sao os desafios do transporte de produtos pereciveis": "necessidade de controle de temperatura e prazos curtos de entrega.",
    "como a flexibilidade na logistica pode ser uma vantagem competitiva": "permite adaptar-se rapidamente a mudancas na demanda.",
    "quais sao as melhores praticas para gerenciar fornecedores na logistica": "estabelecer relacoes de longo prazo e negociar contratos justos.",
    "como a logistica afeta a cadeia de valor da empresa": "influencia os custos, a qualidade e a satisfacao do cliente.",
    "quais sao as implicacoes da digitalizacao na logistica": "melhora a eficiencia e proporciona melhor visibilidade.",
    "como a logistica contribui para a sustentabilidade empresarial": "reduz desperdicios e melhora a eficiencia no uso de recursos.",
    "quais sao os principais componentes de um plano logístico eficaz": "definicao de objetivos, analise de custos e selecao de fornecedores.",
    "como a analise preditiva pode melhorar a logistica": "ajuda a antecipar necessidades e otimizar recursos.",
    "quais sao os impactos das mudancas climaticas na logistica": "afetam rotas, custos e disponibilidades de transporte.",
    "como as parcerias logistica podem aumentar a eficiencia": "compartilham recursos e melhoram o atendimento ao cliente.",

}

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/chat', methods=['POST'])
def chat():
    user_message = request.json.get('message', '').lower()  # Normaliza a mensagem para minúsculas
    user_message = unidecode(user_message)  # Remove acentos

    response = "Desculpe, não entendi a pergunta."

    # Verifica se o usuário deseja sair
    if any(sair_palavra in user_message for sair_palavra in ["sair", "até logo", "tchau", "adeus"]):
        response = "Até logo! Se precisar, volte novamente."
    else:
        # Verifica se a mensagem do usuário contém uma pergunta conhecida
        for pergunta in faq.keys():
            if pergunta in user_message:
                response = faq[pergunta]
                break

    return jsonify({'response': response})

if __name__ == "__main__":
    threading.Thread(target=lambda: webbrowser.open('http://127.0.0.1:5000')).start()
    app.run(debug=True, use_reloader=True)
